### ISSUE TITLE
有一点新的想法

### ISSUE THREAD

**Issue by Zyilin98** [cuit-edu-cn/ruijie-auto-login#1]
有个想法 
网络状态检测。  每隔一定时间检测一次网络通断，如果正常就在log里返回一次正常。如果不正常就尝试重连，连续多次重连失败后，就自动断开，并在log内报错。 这样就可以做到程序开机启动一次就在后台无人值守了
不知道这个实现上会不会很费劲 
我自己不会go 没办法提pr了

**Comment by zzy2210** [comment]
建一个规范些的issue描述吧

**Comment by Zyilin98** [comment]
> 建一个规范些的issue描述吧

感谢回复
已经规范化修改了

**Comment by zzy2210** [comment]
我做了一下拆分，你看一下描述有无问题 issue:  #4

**Comment by Zyilin98** [comment]
> 我做了一下拆分，你看一下描述有无问题 issue: #4

对的没问题
